### ISSUE TITLE
More general repository name?

### ISSUE THREAD

**Issue by Bluscream** [AdguardTeam/AdguardWebsite#5]
I would either suggest creating more repositories for the other websites (blog/aff/mobile/main/forum/etc...) or ( whats the best solution IMO make this repo more general (like AdguardTeam/AduardWebsite for example) and create badges for the different subsites.

- Main
- Mobile
- Forum
- Affiliate

**Comment by vozersky** [comment]
good one, let's make an open bugtracker for all of AdguardWeb
